apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - port: 8081       # port usługi zgodny z wymaganiami labu
      targetPort: 80
      nodePort: 31001
